### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by luvnft** [UXCorpRangel/portfolios-dev#57]
Hi,

Love your website design. Can you help me set it up like this https://uxcorprangel.github.io/portfolios-dev/ I could only set it up with the other options. Can you please email hahz5d@pm.me

**Comment by felixicaza** [comment]
Hi @luvnft, if you want to deploy any of the templates, you can choose the one you want:

unicork-sparkle:
```sh
pnpm create astro@latest -- --template UXCorpRangel/portfolios-dev/unicorn-sparkle
```

rainbow-unicorn:
```sh
pnpx giget@latest gh:UXCorpRangel/portfolios-dev/rainbow-unicorn myPortfolio
```

And choose the service you want to deploy, for example in Astro they have guides for it:
- https://docs.astro.build/en/guides/deploy/

To deploy the `rainbow-unicorn` template, you can use any of the services specified in the Astro documentation, the difference is that this template is made with Vite.

**Comment by luvnft** [comment]
Hi @felixicaza Whats the name of this one https://uxcorprangel.github.io/portfolios-dev/ ?

**Comment by felixicaza** [comment]
That is the main website of the organization and that view is the showcase of this portfolio repository.
